version: '3'

services:
  database-service:
    image: redis:latest
    ports:
      - 6379:6379

  app-service:
    build: app
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - ./app:/usr/src/app
    ports:
      - 80:80
    depends_on:
      - database-service

  website-service:
    build: website
    command: python app.py
    volumes:
      - ./website:/usr/src/app
    ports:
      - 5002:80

networks:
  default:
    name: my_network
