version: '3'

services:

  mongodb:
    image: mongo:4
    container_name: mongodb
    restart: always
    environment:
      # MONGO_INITDB_DATABASE:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb-volume:/data/db

  app:
    container_name: app
    build: .
    image: app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      - mongodb

volumes:
  mongodb-volume:

networks:
  default:
    external:
      name: my_network
