version: "3"

services:

  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_volume:/data/postgresql

  app:
    build: .
    container_name: app
    image: app
    env_file:
      - os.env
    command: bash -c 'while !</dev/tcp/postgresql/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgresql

volumes:
  postgresql_volume:

networks:
  mynetwork:
