# Compose file defines: services, volumes, and networks

# Version of the config file
version: '3'

services:

  service_1:
    # Build and run a local image
    build: <path>  # It will search for Dockerfile in path

    # Equivalent to
    build:
      # Working dir
      context: <path>
      # Image's Dockerfile
      dockerfile: <Dockerfile_path>

    # Or directly specify an existing image (either locally on in Docker Hub)
    image: <my_image>

    # restart: "always" will start the container on startup and on failure
    # "no" is the default value - "on-failure" will restart only on failure
    restart: always

    # Command to be run when service is up
    command: <executable> <param_1>

    # Env variables - key:value
    environment:
      - ENVIRONMENT=local

    # Or importing a file - .env type
    env_file:
      - <env_file_path>

    # ENV variables can be accessed from docker-compose.yml (and other config
    # files) using ${<var_name>}

    # Ports to expose - mapping from container to the outside world
    ports:
      - "<host_port>:<container_port>"

    # Attach a volume
    volumes:
      # By path
      - <host_path>:<container_path>
      # Or by name
      - <volume_name>:<container_path>

    # To join network/s
    networks:
      - <network_name>

    # Services dependencies
    depends_on:
      # Service here will be start even if not called directly
      - service_2

  service_2:
    image: <image_name_2>

# Create volumes
volumes:
  # Volumes can take different options, but if set empty they will take the
  # default configuration
  <volume_name>:
    external: true
    name: <volume_name>

# Virtual network information
networks:
  # Set up here default network if necessary
  default:
    # Joining an existing network
    external:
      name: <pre_existing_network_name>

  # Create a new network
  <network_name>:
    name: <network_name>
