# Version of the config file
version: '3'

services:

  service_1:
    # Build and run a local image
    build:
      # Working dir
      context: .
      # Image's Dockerfile
      dockerfile: Dockerfile

    # Or directly specify an existing image (either locally on in Docker Hub)
    image: my_image

    # restart: "always" will start the container on startup and on failure
    # "no" is the default value - "on-failure" will restart only on failure
    restart: always

    # Command to be run when service is up
    command: python app.py

    # Env variables - key:value
    environment:
      - ENVIRONMENT=local

    # Ports to expose - mapping from container to the outside world
    ports:
      - "<host_port>:<container_port>"

    # Attach a volume
    volumes:
      - .:/code
      - logvolume01:/var/log

    # Services dependencies
    depends_on:
      - service_2

  service_2:
    image: my_image_2

volumes:
  logvolume01: {}

# Virtual network information
networks:
  default:
    external:
      name: my_network
