version: '3'

services:

  service_1:
    # Working dir
    build: ../Docker

    # Or
    build:
      # Working dir
      context: ../Docker
      # Dockerfile to be run
      dockerfile: ../Docker/Dockerfile

    # To directly specify an image
    image: my_image

    # restart: "always" will start the container on startup and on failure
    # "no" is the default value - "on-failure" will restart only on failure
    restart: always

    # Command to be run when service is up
    command: python app.py

    # Env variables
    environment:
      - ENVIRONMENT=local

    # Ports to expose - mapping from container to the outside world
    ports:
      - "5000:5000"

    volumes:
      - .:/code
      - logvolume01:/var/log

    # Services dependencies
    depends_on:
      - service_2

  service_2:
    image: my_image_2

volumes:
  logvolume01: {}

networks:
  default:
    external:
      name: my_network
