version: '3'

services:

  service_1:
    build: .
    image: my_image
    command: python app.py
    environment:
      - ENVIRONMENT=local
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log

  service_2:
    image: my_image_2

volumes:
  logvolume01: {}

networks:
  default:
    external:
      name: my_network

